services:
  # Nome do serviço, pode ser o que quiser
  gan_dev_env:
    build: .
    # Habilita o runtime da NVIDIA para acesso à GPU
    runtime: nvidia
    # Mapeia a porta para o caso de querer usar o Jupyter no navegador
    ports:
      - "8888:8888"
    # Define as variáveis de ambiente necessárias
    environment:
      - TF_CPP_MIN_LOG_LEVEL=2
    # Mapeia a pasta inteira do projeto para dentro do container
    volumes:
      - .:/tf/TCC_GAN
    # Define o diretório de trabalho padrão
    working_dir: /tf/TCC_GAN